/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccountInfo {
  'username' : string,
  'displayName' : string,
  'role' : Role,
  'linkedEmployeeId' : [] | [string],
}
export interface Applicant {
  'id' : string,
  'contact' : string,
  'jobPostingId' : string,
  'name' : string,
  'resumeNotes' : string,
  'stage' : ApplicantStage,
  'appliedDate' : bigint,
}
export type ApplicantStage = { 'hired' : null } |
  { 'offer' : null } |
  { 'screening' : null } |
  { 'interview' : null } |
  { 'applied' : null } |
  { 'rejected' : null };
export interface CreateEmployeeWithAccountInput {
  'username' : string,
  'displayName' : string,
  'directManagerId' : [] | [string],
  'passwordHash' : string,
  'profile' : Employee,
}
export interface Employee {
  'id' : string,
  'status' : EmployeeStatus,
  'role' : Role,
  'directManagerId' : [] | [string],
  'fullName' : string,
  'email' : string,
  'jobTitle' : string,
  'badgeId' : string,
  'phone' : string,
  'department' : string,
  'profileImageUrl' : [] | [string],
  'linkedAccountUsername' : [] | [string],
  'startDate' : bigint,
}
export type EmployeeStatus = { 'active' : null } |
  { 'terminated' : null } |
  { 'inactive' : null };
export interface JobPosting {
  'id' : string,
  'status' : JobPostingStatus,
  'title' : string,
  'description' : string,
  'department' : string,
}
export type JobPostingStatus = { 'closed' : null } |
  { 'open' : null } |
  { 'draft' : null };
export type LinkEmployeeAccountResult = { 'ok' : null } |
  { 'err' : string };
export interface LinkEmployeeToAccountInput {
  'accountUsername' : string,
  'employeeId' : string,
}
export interface Notification {
  'id' : string,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'isRead' : boolean,
  'relatedEntityId' : [] | [string],
  'message' : string,
  'recipientUsername' : string,
}
export type NotificationType = { 'timeOffDenied' : null } |
  { 'scheduleUnpublished' : null } |
  { 'schedulePublished' : null } |
  { 'timeOffSubmitted' : null } |
  { 'timeOffApproved' : null } |
  { 'urgentAlert' : null };
export interface PTOBalance {
  'balance' : number,
  'employeeId' : string,
  'policyId' : string,
}
export interface PTOPolicy {
  'id' : string,
  'name' : string,
  'accrualRate' : number,
  'eligibleLeaveTypes' : Array<string>,
  'maxCarryOver' : number,
}
export type Role = { 'supervisor' : null } |
  { 'manager' : null } |
  { 'hrAdmin' : null } |
  { 'employee' : null };
export type ServiceResult = { 'ok' : null } |
  { 'err' : string };
export type ServiceResult_1 = { 'ok' : bigint } |
  { 'err' : string };
export type ServiceResult_2 = { 'ok' : Timesheet } |
  { 'err' : string };
export type ServiceResult_3 = { 'ok' : string } |
  { 'err' : string };
export type ServiceResult_4 = { 'ok' : UserProfile } |
  { 'err' : string };
export type ServiceResult_5 = { 'ok' : Array<AccountInfo> } |
  { 'err' : string };
export type ServiceResult_6 = { 'ok' : Array<Notification> } |
  { 'err' : string };
export type ServiceResult_7 = { 'ok' : Employee } |
  { 'err' : string };
export interface Shift {
  'id' : string,
  'startTime' : bigint,
  'status' : ShiftStatus,
  'endTime' : bigint,
  'date' : bigint,
  'employeeId' : string,
  'department' : string,
}
export type ShiftStatus = { 'published' : null } |
  { 'draft' : null };
export interface TimeOffRequest {
  'id' : string,
  'status' : TimeOffStatus,
  'endDate' : bigint,
  'approverComments' : [] | [string],
  'timeOffType' : string,
  'employeeId' : string,
  'requestDate' : bigint,
  'startDate' : bigint,
}
export type TimeOffStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface Timesheet {
  'id' : string,
  'status' : TimesheetStatus,
  'employeeUsername' : string,
  'weekStartDate' : string,
  'totalHours' : number,
  'submittedAt' : bigint,
  'hrComment' : [] | [string],
  'entries' : Array<TimesheetEntry>,
  'employeeId' : string,
  'managerComment' : [] | [string],
}
export interface TimesheetEntry {
  'startTime' : string,
  'endTime' : string,
  'date' : string,
  'hoursWorked' : number,
  'buildingNumber' : [] | [string],
}
export type TimesheetStatus = { 'managerApproved' : null } |
  { 'submitted' : null } |
  { 'hrDenied' : null } |
  { 'managerDenied' : null } |
  { 'hrApproved' : null };
export interface UserProfile {
  'username' : string,
  'role' : Role,
  'employeeId' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addApplicant' : ActorMethod<[Applicant], undefined>,
  'addPTOBalance' : ActorMethod<[PTOBalance], undefined>,
  'addPTOPolicy' : ActorMethod<[PTOPolicy], undefined>,
  'approveTimeOffRequest' : ActorMethod<[string], undefined>,
  'approveTimeOffRequestWithComment' : ActorMethod<[string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignShift' : ActorMethod<[Shift], undefined>,
  'createAccount' : ActorMethod<[string, string, string, Role], undefined>,
  'createEmployee' : ActorMethod<[Employee], undefined>,
  'createEmployeeWithAccount' : ActorMethod<
    [CreateEmployeeWithAccountInput],
    undefined
  >,
  'createJobPosting' : ActorMethod<[JobPosting], undefined>,
  'deactivateEmployee' : ActorMethod<[string], undefined>,
  'deleteEmployee' : ActorMethod<[string], ServiceResult>,
  'deleteShift' : ActorMethod<[string], undefined>,
  'denyTimeOffRequest' : ActorMethod<[string, string], undefined>,
  'getAllApplicants' : ActorMethod<[], Array<Applicant>>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllPTOPolicies' : ActorMethod<[], Array<PTOPolicy>>,
  'getAllShiftsForDepartment' : ActorMethod<[string], Array<Shift>>,
  'getAllShiftsForEmployee' : ActorMethod<[string], Array<Shift>>,
  'getAllTimeOffRequestsForEmployee' : ActorMethod<
    [string],
    Array<TimeOffRequest>
  >,
  'getApplicant' : ActorMethod<[string], Applicant>,
  'getApplicantsForPosting' : ActorMethod<[string], Array<Applicant>>,
  'getAvailableShifts' : ActorMethod<[string], Array<Shift>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEmployee' : ActorMethod<[string], Employee>,
  'getEmployeeByBadgeId' : ActorMethod<[string], ServiceResult_7>,
  'getEmployeesByRole' : ActorMethod<[Role], Array<Employee>>,
  'getJobPosting' : ActorMethod<[string], JobPosting>,
  'getNotifications' : ActorMethod<[], ServiceResult_6>,
  'getPTOBalance' : ActorMethod<[string], PTOBalance>,
  'getPTOPolicy' : ActorMethod<[string], PTOPolicy>,
  'getShifts' : ActorMethod<[], Array<Shift>>,
  'getTimeOffRequests' : ActorMethod<[], Array<TimeOffRequest>>,
  'getTimesheets' : ActorMethod<[], Array<Timesheet>>,
  'getUnlinkedAccounts' : ActorMethod<[], ServiceResult_5>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasConflictingShift' : ActorMethod<[Shift], boolean>,
  'hrReviewTimesheet' : ActorMethod<[string, boolean, string], ServiceResult_3>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkEmployeeToAccount' : ActorMethod<
    [LinkEmployeeToAccountInput],
    LinkEmployeeAccountResult
  >,
  'login' : ActorMethod<[string, string], [] | [UserProfile]>,
  'loginWithBadgeId' : ActorMethod<[string], ServiceResult_4>,
  'managerReviewTimesheet' : ActorMethod<
    [string, boolean, string],
    ServiceResult_3
  >,
  'markAllNotificationsRead' : ActorMethod<[], ServiceResult>,
  'markNotificationRead' : ActorMethod<[string], ServiceResult>,
  'publishSchedule' : ActorMethod<[string, bigint], ServiceResult_1>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendUrgentAlert' : ActorMethod<[string], ServiceResult>,
  'setRole' : ActorMethod<[string, Role], undefined>,
  'submitTimeOffRequest' : ActorMethod<[TimeOffRequest], undefined>,
  'submitTimesheet' : ActorMethod<[Timesheet], ServiceResult_2>,
  'unpublishSchedule' : ActorMethod<[string, bigint], ServiceResult_1>,
  'updateApplicantStage' : ActorMethod<[string, ApplicantStage], undefined>,
  'updateEmployee' : ActorMethod<[string, Employee], undefined>,
  'updateEmployeeProfile' : ActorMethod<
    [string, string, string, [] | [string]],
    ServiceResult
  >,
  'updateJobPosting' : ActorMethod<[string, JobPosting], undefined>,
  'updatePTOBalance' : ActorMethod<[PTOBalance], undefined>,
  'updatePTOPolicy' : ActorMethod<[PTOPolicy], undefined>,
  'validateSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];