/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ServiceResult_4 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface CreateEmployeeWithAccountInput {
    username: string;
    displayName: string;
    directManagerId?: string;
    passwordHash: string;
    profile: Employee;
}
export interface TimesheetEntry {
    startTime: string;
    endTime: string;
    date: string;
    hoursWorked: number;
}
export type ServiceResult_1 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface Shift {
    id: string;
    startTime: bigint;
    status: ShiftStatus;
    endTime: bigint;
    date: bigint;
    employeeId: string;
    department: string;
}
export interface JobPosting {
    id: string;
    status: JobPostingStatus;
    title: string;
    description: string;
    department: string;
}
export interface Timesheet {
    id: string;
    status: TimesheetStatus;
    employeeUsername: string;
    weekStartDate: string;
    totalHours: number;
    submittedAt: bigint;
    hrComment?: string;
    entries: Array<TimesheetEntry>;
    employeeId: string;
    managerComment?: string;
}
export interface PTOPolicy {
    id: string;
    name: string;
    accrualRate: number;
    eligibleLeaveTypes: Array<string>;
    maxCarryOver: number;
}
export interface Applicant {
    id: string;
    contact: string;
    jobPostingId: string;
    name: string;
    resumeNotes: string;
    stage: ApplicantStage;
    appliedDate: bigint;
}
export type ServiceResult_2 = {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
};
export interface PTOBalance {
    balance: number;
    employeeId: string;
    policyId: string;
}
export interface Employee {
    id: string;
    status: EmployeeStatus;
    role: Role;
    directManagerId?: string;
    fullName: string;
    email: string;
    jobTitle: string;
    badgeId: string;
    phone: string;
    department: string;
    startDate: bigint;
}
export type ServiceResult_3 = {
    __kind__: "ok";
    ok: Employee;
} | {
    __kind__: "err";
    err: string;
};
export type ServiceResult = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface TimeOffRequest {
    id: string;
    status: TimeOffStatus;
    endDate: bigint;
    approverComments?: string;
    timeOffType: string;
    employeeId: string;
    requestDate: bigint;
    startDate: bigint;
}
export interface UserProfile {
    username: string;
    role: Role;
    employeeId?: string;
}
export enum ApplicantStage {
    hired = "hired",
    offer = "offer",
    screening = "screening",
    interview = "interview",
    applied = "applied",
    rejected = "rejected"
}
export enum EmployeeStatus {
    active = "active",
    terminated = "terminated",
    inactive = "inactive"
}
export enum JobPostingStatus {
    closed = "closed",
    open = "open",
    draft = "draft"
}
export enum Role {
    supervisor = "supervisor",
    manager = "manager",
    hrAdmin = "hrAdmin",
    employee = "employee"
}
export enum ShiftStatus {
    published = "published",
    draft = "draft"
}
export enum TimeOffStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum TimesheetStatus {
    managerApproved = "managerApproved",
    submitted = "submitted",
    hrDenied = "hrDenied",
    managerDenied = "managerDenied",
    hrApproved = "hrApproved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addApplicant(applicant: Applicant): Promise<void>;
    addPTOBalance(balance: PTOBalance): Promise<void>;
    addPTOPolicy(policy: PTOPolicy): Promise<void>;
    approveTimeOffRequest(requestId: string): Promise<void>;
    approveTimeOffRequestWithComment(requestId: string, comment: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignShift(shift: Shift): Promise<void>;
    createAccount(displayName: string, username: string, passwordHash: string, role: Role): Promise<void>;
    createEmployee(profile: Employee): Promise<void>;
    createEmployeeWithAccount(input: CreateEmployeeWithAccountInput): Promise<void>;
    createJobPosting(posting: JobPosting): Promise<void>;
    deactivateEmployee(id: string): Promise<void>;
    deleteEmployee(id: string): Promise<ServiceResult_4>;
    deleteShift(id: string): Promise<void>;
    denyTimeOffRequest(requestId: string, comments: string): Promise<void>;
    getAllApplicants(): Promise<Array<Applicant>>;
    getAllEmployees(): Promise<Array<Employee>>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getAllPTOPolicies(): Promise<Array<PTOPolicy>>;
    getAllShiftsForDepartment(department: string): Promise<Array<Shift>>;
    getAllShiftsForEmployee(employeeId: string): Promise<Array<Shift>>;
    getAllTimeOffRequests(): Promise<Array<TimeOffRequest>>;
    getAllTimeOffRequestsForEmployee(employeeId: string): Promise<Array<TimeOffRequest>>;
    getApplicant(id: string): Promise<Applicant>;
    getApplicantsForPosting(jobPostingId: string): Promise<Array<Applicant>>;
    getAvailableShifts(dep: string): Promise<Array<Shift>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEmployee(id: string): Promise<Employee>;
    getEmployeeByBadgeId(badgeId: string): Promise<ServiceResult_3>;
    getEmployeesByRole(role: Role): Promise<Array<Employee>>;
    getJobPosting(id: string): Promise<JobPosting>;
    getPTOBalance(employeeId: string): Promise<PTOBalance>;
    getPTOPolicy(policyId: string): Promise<PTOPolicy>;
    getTimesheets(): Promise<Array<Timesheet>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasConflictingShift(newShift: Shift): Promise<boolean>;
    hrReviewTimesheet(id: string, approved: boolean, comment: string): Promise<ServiceResult_1>;
    isCallerAdmin(): Promise<boolean>;
    login(username: string, passwordHash: string): Promise<UserProfile | null>;
    loginWithBadgeId(badgeId: string): Promise<ServiceResult_2>;
    managerReviewTimesheet(id: string, approved: boolean, comment: string): Promise<ServiceResult_1>;
    publishSchedule(department: string, weekStart: bigint): Promise<ServiceResult>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRole(username: string, role: Role): Promise<void>;
    submitTimeOffRequest(request: TimeOffRequest): Promise<void>;
    submitTimesheet(timesheet: Timesheet): Promise<ServiceResult_1>;
    unpublishSchedule(department: string, weekStart: bigint): Promise<ServiceResult>;
    updateApplicantStage(id: string, stage: ApplicantStage): Promise<void>;
    updateEmployee(id: string, profile: Employee): Promise<void>;
    updateJobPosting(id: string, posting: JobPosting): Promise<void>;
    updatePTOBalance(balance: PTOBalance): Promise<void>;
    updatePTOPolicy(policy: PTOPolicy): Promise<void>;
    validateSession(username: string): Promise<boolean>;
}
import type { Applicant as _Applicant, ApplicantStage as _ApplicantStage, CreateEmployeeWithAccountInput as _CreateEmployeeWithAccountInput, Employee as _Employee, EmployeeStatus as _EmployeeStatus, JobPosting as _JobPosting, JobPostingStatus as _JobPostingStatus, Role as _Role, ServiceResult as _ServiceResult, ServiceResult_1 as _ServiceResult_1, ServiceResult_2 as _ServiceResult_2, ServiceResult_3 as _ServiceResult_3, ServiceResult_4 as _ServiceResult_4, Shift as _Shift, ShiftStatus as _ShiftStatus, TimeOffRequest as _TimeOffRequest, TimeOffStatus as _TimeOffStatus, Timesheet as _Timesheet, TimesheetEntry as _TimesheetEntry, TimesheetStatus as _TimesheetStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addApplicant(arg0: Applicant): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addApplicant(to_candid_Applicant_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApplicant(to_candid_Applicant_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPTOBalance(arg0: PTOBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPTOBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPTOBalance(arg0);
            return result;
        }
    }
    async addPTOPolicy(arg0: PTOPolicy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPTOPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPTOPolicy(arg0);
            return result;
        }
    }
    async approveTimeOffRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTimeOffRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTimeOffRequest(arg0);
            return result;
        }
    }
    async approveTimeOffRequestWithComment(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTimeOffRequestWithComment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTimeOffRequestWithComment(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignShift(arg0: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignShift(to_candid_Shift_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignShift(to_candid_Shift_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createAccount(arg0: string, arg1: string, arg2: string, arg3: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAccount(arg0, arg1, arg2, to_candid_Role_n11(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAccount(arg0, arg1, arg2, to_candid_Role_n11(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async createEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(to_candid_Employee_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(to_candid_Employee_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createEmployeeWithAccount(arg0: CreateEmployeeWithAccountInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployeeWithAccount(to_candid_CreateEmployeeWithAccountInput_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployeeWithAccount(to_candid_CreateEmployeeWithAccountInput_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createJobPosting(arg0: JobPosting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(to_candid_JobPosting_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(to_candid_JobPosting_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateEmployee(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateEmployee(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: string): Promise<ServiceResult_4> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return from_candid_ServiceResult_4_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return from_candid_ServiceResult_4_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteShift(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShift(arg0);
            return result;
        }
    }
    async denyTimeOffRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyTimeOffRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyTimeOffRequest(arg0, arg1);
            return result;
        }
    }
    async getAllApplicants(): Promise<Array<Applicant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApplicants();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApplicants();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPTOPolicies(): Promise<Array<PTOPolicy>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPTOPolicies();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPTOPolicies();
            return result;
        }
    }
    async getAllShiftsForDepartment(arg0: string): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShiftsForDepartment(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShiftsForDepartment(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShiftsForEmployee(arg0: string): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShiftsForEmployee(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShiftsForEmployee(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimeOffRequests(): Promise<Array<TimeOffRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimeOffRequests();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimeOffRequests();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTimeOffRequestsForEmployee(arg0: string): Promise<Array<TimeOffRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTimeOffRequestsForEmployee(arg0);
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTimeOffRequestsForEmployee(arg0);
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicant(arg0: string): Promise<Applicant> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicant(arg0);
                return from_candid_Applicant_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicant(arg0);
            return from_candid_Applicant_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicantsForPosting(arg0: string): Promise<Array<Applicant>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicantsForPosting(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicantsForPosting(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableShifts(arg0: string): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableShifts(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableShifts(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployee(arg0: string): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeeByBadgeId(arg0: string): Promise<ServiceResult_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeeByBadgeId(arg0);
                return from_candid_ServiceResult_3_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeeByBadgeId(arg0);
            return from_candid_ServiceResult_3_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployeesByRole(arg0: Role): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployeesByRole(to_candid_Role_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployeesByRole(to_candid_Role_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobPosting(arg0: string): Promise<JobPosting> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPosting(arg0);
                return from_candid_JobPosting_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPosting(arg0);
            return from_candid_JobPosting_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPTOBalance(arg0: string): Promise<PTOBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getPTOBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPTOBalance(arg0);
            return result;
        }
    }
    async getPTOPolicy(arg0: string): Promise<PTOPolicy> {
        if (this.processError) {
            try {
                const result = await this.actor.getPTOPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPTOPolicy(arg0);
            return result;
        }
    }
    async getTimesheets(): Promise<Array<Timesheet>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimesheets();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimesheets();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasConflictingShift(arg0: Shift): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasConflictingShift(to_candid_Shift_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasConflictingShift(to_candid_Shift_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async hrReviewTimesheet(arg0: string, arg1: boolean, arg2: string): Promise<ServiceResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.hrReviewTimesheet(arg0, arg1, arg2);
                return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hrReviewTimesheet(arg0, arg1, arg2);
            return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginWithBadgeId(arg0: string): Promise<ServiceResult_2> {
        if (this.processError) {
            try {
                const result = await this.actor.loginWithBadgeId(arg0);
                return from_candid_ServiceResult_2_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginWithBadgeId(arg0);
            return from_candid_ServiceResult_2_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async managerReviewTimesheet(arg0: string, arg1: boolean, arg2: string): Promise<ServiceResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.managerReviewTimesheet(arg0, arg1, arg2);
                return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.managerReviewTimesheet(arg0, arg1, arg2);
            return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishSchedule(arg0: string, arg1: bigint): Promise<ServiceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.publishSchedule(arg0, arg1);
                return from_candid_ServiceResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishSchedule(arg0, arg1);
            return from_candid_ServiceResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n71(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setRole(arg0: string, arg1: Role): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRole(arg0, to_candid_Role_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRole(arg0, to_candid_Role_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitTimeOffRequest(arg0: TimeOffRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTimeOffRequest(to_candid_TimeOffRequest_n73(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTimeOffRequest(to_candid_TimeOffRequest_n73(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitTimesheet(arg0: Timesheet): Promise<ServiceResult_1> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTimesheet(to_candid_Timesheet_n77(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTimesheet(to_candid_Timesheet_n77(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ServiceResult_1_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async unpublishSchedule(arg0: string, arg1: bigint): Promise<ServiceResult> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishSchedule(arg0, arg1);
                return from_candid_ServiceResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishSchedule(arg0, arg1);
            return from_candid_ServiceResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateApplicantStage(arg0: string, arg1: ApplicantStage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateApplicantStage(arg0, to_candid_ApplicantStage_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateApplicantStage(arg0, to_candid_ApplicantStage_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEmployee(arg0: string, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, to_candid_Employee_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateJobPosting(arg0: string, arg1: JobPosting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJobPosting(arg0, to_candid_JobPosting_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJobPosting(arg0, to_candid_JobPosting_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePTOBalance(arg0: PTOBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePTOBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePTOBalance(arg0);
            return result;
        }
    }
    async updatePTOPolicy(arg0: PTOPolicy): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePTOPolicy(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePTOPolicy(arg0);
            return result;
        }
    }
    async validateSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateSession(arg0);
            return result;
        }
    }
}
function from_candid_ApplicantStage_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicantStage): ApplicantStage {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_Applicant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Applicant): Applicant {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_EmployeeStatus_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmployeeStatus): EmployeeStatus {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Employee_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Employee {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_JobPostingStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPostingStatus): JobPostingStatus {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceResult_1_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceResult_1): ServiceResult_1 {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceResult_2_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceResult_2): ServiceResult_2 {
    return from_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceResult_3_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceResult_3): ServiceResult_3 {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceResult_4_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceResult_4): ServiceResult_4 {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceResult_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceResult): ServiceResult {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_ShiftStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShiftStatus): ShiftStatus {
    return from_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function from_candid_Shift_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Shift): Shift {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_TimeOffRequest_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeOffRequest): TimeOffRequest {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_TimeOffStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimeOffStatus): TimeOffStatus {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function from_candid_TimesheetStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TimesheetStatus): TimesheetStatus {
    return from_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function from_candid_Timesheet_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Timesheet): Timesheet {
    return from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contact: string;
    jobPostingId: string;
    name: string;
    resumeNotes: string;
    stage: _ApplicantStage;
    appliedDate: bigint;
}): {
    id: string;
    contact: string;
    jobPostingId: string;
    name: string;
    resumeNotes: string;
    stage: ApplicantStage;
    appliedDate: bigint;
} {
    return {
        id: value.id,
        contact: value.contact,
        jobPostingId: value.jobPostingId,
        name: value.name,
        resumeNotes: value.resumeNotes,
        stage: from_candid_ApplicantStage_n28(_uploadFile, _downloadFile, value.stage),
        appliedDate: value.appliedDate
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EmployeeStatus;
    role: _Role;
    directManagerId: [] | [string];
    fullName: string;
    email: string;
    jobTitle: string;
    badgeId: string;
    phone: string;
    department: string;
    startDate: bigint;
}): {
    id: string;
    status: EmployeeStatus;
    role: Role;
    directManagerId?: string;
    fullName: string;
    email: string;
    jobTitle: string;
    badgeId: string;
    phone: string;
    department: string;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EmployeeStatus_n33(_uploadFile, _downloadFile, value.status),
        role: from_candid_Role_n35(_uploadFile, _downloadFile, value.role),
        directManagerId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.directManagerId)),
        fullName: value.fullName,
        email: value.email,
        jobTitle: value.jobTitle,
        badgeId: value.badgeId,
        phone: value.phone,
        department: value.department,
        startDate: value.startDate
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _JobPostingStatus;
    title: string;
    description: string;
    department: string;
}): {
    id: string;
    status: JobPostingStatus;
    title: string;
    description: string;
    department: string;
} {
    return {
        id: value.id,
        status: from_candid_JobPostingStatus_n41(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        department: value.department
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    status: _ShiftStatus;
    endTime: bigint;
    date: bigint;
    employeeId: string;
    department: string;
}): {
    id: string;
    startTime: bigint;
    status: ShiftStatus;
    endTime: bigint;
    date: bigint;
    employeeId: string;
    department: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: from_candid_ShiftStatus_n46(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime,
        date: value.date,
        employeeId: value.employeeId,
        department: value.department
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TimeOffStatus;
    endDate: bigint;
    approverComments: [] | [string];
    timeOffType: string;
    employeeId: string;
    requestDate: bigint;
    startDate: bigint;
}): {
    id: string;
    status: TimeOffStatus;
    endDate: bigint;
    approverComments?: string;
    timeOffType: string;
    employeeId: string;
    requestDate: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TimeOffStatus_n51(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        approverComments: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.approverComments)),
        timeOffType: value.timeOffType,
        employeeId: value.employeeId,
        requestDate: value.requestDate,
        startDate: value.startDate
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: _Role;
    employeeId: [] | [string];
}): {
    username: string;
    role: Role;
    employeeId?: string;
} {
    return {
        username: value.username,
        role: from_candid_Role_n35(_uploadFile, _downloadFile, value.role),
        employeeId: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.employeeId))
    };
}
function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TimesheetStatus;
    employeeUsername: string;
    weekStartDate: string;
    totalHours: number;
    submittedAt: bigint;
    hrComment: [] | [string];
    entries: Array<_TimesheetEntry>;
    employeeId: string;
    managerComment: [] | [string];
}): {
    id: string;
    status: TimesheetStatus;
    employeeUsername: string;
    weekStartDate: string;
    totalHours: number;
    submittedAt: bigint;
    hrComment?: string;
    entries: Array<TimesheetEntry>;
    employeeId: string;
    managerComment?: string;
} {
    return {
        id: value.id,
        status: from_candid_TimesheetStatus_n63(_uploadFile, _downloadFile, value.status),
        employeeUsername: value.employeeUsername,
        weekStartDate: value.weekStartDate,
        totalHours: value.totalHours,
        submittedAt: value.submittedAt,
        hrComment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.hrComment)),
        entries: value.entries,
        employeeId: value.employeeId,
        managerComment: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.managerComment))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
}): ApplicantStage {
    return "hired" in value ? ApplicantStage.hired : "offer" in value ? ApplicantStage.offer : "screening" in value ? ApplicantStage.screening : "interview" in value ? ApplicantStage.interview : "applied" in value ? ApplicantStage.applied : "rejected" in value ? ApplicantStage.rejected : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    terminated: null;
} | {
    inactive: null;
}): EmployeeStatus {
    return "active" in value ? EmployeeStatus.active : "terminated" in value ? EmployeeStatus.terminated : "inactive" in value ? EmployeeStatus.inactive : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    supervisor: null;
} | {
    manager: null;
} | {
    hrAdmin: null;
} | {
    employee: null;
}): Role {
    return "supervisor" in value ? Role.supervisor : "manager" in value ? Role.manager : "hrAdmin" in value ? Role.hrAdmin : "employee" in value ? Role.employee : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
}): JobPostingStatus {
    return "closed" in value ? JobPostingStatus.closed : "open" in value ? JobPostingStatus.open : "draft" in value ? JobPostingStatus.draft : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): ShiftStatus {
    return "published" in value ? ShiftStatus.published : "draft" in value ? ShiftStatus.draft : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): TimeOffStatus {
    return "pending" in value ? TimeOffStatus.pending : "denied" in value ? TimeOffStatus.denied : "approved" in value ? TimeOffStatus.approved : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Employee;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Employee;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Employee_n31(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    managerApproved: null;
} | {
    submitted: null;
} | {
    hrDenied: null;
} | {
    managerDenied: null;
} | {
    hrApproved: null;
}): TimesheetStatus {
    return "managerApproved" in value ? TimesheetStatus.managerApproved : "submitted" in value ? TimesheetStatus.submitted : "hrDenied" in value ? TimesheetStatus.hrDenied : "managerDenied" in value ? TimesheetStatus.managerDenied : "hrApproved" in value ? TimesheetStatus.hrApproved : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserProfile_n54(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Applicant>): Array<Applicant> {
    return value.map((x)=>from_candid_Applicant_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Array<Employee> {
    return value.map((x)=>from_candid_Employee_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Shift>): Array<Shift> {
    return value.map((x)=>from_candid_Shift_n44(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TimeOffRequest>): Array<TimeOffRequest> {
    return value.map((x)=>from_candid_TimeOffRequest_n49(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Timesheet>): Array<Timesheet> {
    return value.map((x)=>from_candid_Timesheet_n61(_uploadFile, _downloadFile, x));
}
function to_candid_ApplicantStage_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicantStage): _ApplicantStage {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Applicant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Applicant): _Applicant {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateEmployeeWithAccountInput_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateEmployeeWithAccountInput): _CreateEmployeeWithAccountInput {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_EmployeeStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): _EmployeeStatus {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_Employee_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): _Employee {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_JobPostingStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPostingStatus): _JobPostingStatus {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_JobPosting_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPosting): _JobPosting {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ShiftStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShiftStatus): _ShiftStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Shift_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Shift): _Shift {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_TimeOffRequest_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOffRequest): _TimeOffRequest {
    return to_candid_record_n74(_uploadFile, _downloadFile, value);
}
function to_candid_TimeOffStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOffStatus): _TimeOffStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_TimesheetStatus_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimesheetStatus): _TimesheetStatus {
    return to_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function to_candid_Timesheet_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timesheet): _Timesheet {
    return to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n72(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: EmployeeStatus;
    role: Role;
    directManagerId?: string;
    fullName: string;
    email: string;
    jobTitle: string;
    badgeId: string;
    phone: string;
    department: string;
    startDate: bigint;
}): {
    id: string;
    status: _EmployeeStatus;
    role: _Role;
    directManagerId: [] | [string];
    fullName: string;
    email: string;
    jobTitle: string;
    badgeId: string;
    phone: string;
    department: string;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: to_candid_EmployeeStatus_n15(_uploadFile, _downloadFile, value.status),
        role: to_candid_Role_n11(_uploadFile, _downloadFile, value.role),
        directManagerId: value.directManagerId ? candid_some(value.directManagerId) : candid_none(),
        fullName: value.fullName,
        email: value.email,
        jobTitle: value.jobTitle,
        badgeId: value.badgeId,
        phone: value.phone,
        department: value.department,
        startDate: value.startDate
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    displayName: string;
    directManagerId?: string;
    passwordHash: string;
    profile: Employee;
}): {
    username: string;
    displayName: string;
    directManagerId: [] | [string];
    passwordHash: string;
    profile: _Employee;
} {
    return {
        username: value.username,
        displayName: value.displayName,
        directManagerId: value.directManagerId ? candid_some(value.directManagerId) : candid_none(),
        passwordHash: value.passwordHash,
        profile: to_candid_Employee_n13(_uploadFile, _downloadFile, value.profile)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    contact: string;
    jobPostingId: string;
    name: string;
    resumeNotes: string;
    stage: ApplicantStage;
    appliedDate: bigint;
}): {
    id: string;
    contact: string;
    jobPostingId: string;
    name: string;
    resumeNotes: string;
    stage: _ApplicantStage;
    appliedDate: bigint;
} {
    return {
        id: value.id,
        contact: value.contact,
        jobPostingId: value.jobPostingId,
        name: value.name,
        resumeNotes: value.resumeNotes,
        stage: to_candid_ApplicantStage_n3(_uploadFile, _downloadFile, value.stage),
        appliedDate: value.appliedDate
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: JobPostingStatus;
    title: string;
    description: string;
    department: string;
}): {
    id: string;
    status: _JobPostingStatus;
    title: string;
    description: string;
    department: string;
} {
    return {
        id: value.id,
        status: to_candid_JobPostingStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        description: value.description,
        department: value.department
    };
}
function to_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    role: Role;
    employeeId?: string;
}): {
    username: string;
    role: _Role;
    employeeId: [] | [string];
} {
    return {
        username: value.username,
        role: to_candid_Role_n11(_uploadFile, _downloadFile, value.role),
        employeeId: value.employeeId ? candid_some(value.employeeId) : candid_none()
    };
}
function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TimeOffStatus;
    endDate: bigint;
    approverComments?: string;
    timeOffType: string;
    employeeId: string;
    requestDate: bigint;
    startDate: bigint;
}): {
    id: string;
    status: _TimeOffStatus;
    endDate: bigint;
    approverComments: [] | [string];
    timeOffType: string;
    employeeId: string;
    requestDate: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        status: to_candid_TimeOffStatus_n75(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        approverComments: value.approverComments ? candid_some(value.approverComments) : candid_none(),
        timeOffType: value.timeOffType,
        employeeId: value.employeeId,
        requestDate: value.requestDate,
        startDate: value.startDate
    };
}
function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TimesheetStatus;
    employeeUsername: string;
    weekStartDate: string;
    totalHours: number;
    submittedAt: bigint;
    hrComment?: string;
    entries: Array<TimesheetEntry>;
    employeeId: string;
    managerComment?: string;
}): {
    id: string;
    status: _TimesheetStatus;
    employeeUsername: string;
    weekStartDate: string;
    totalHours: number;
    submittedAt: bigint;
    hrComment: [] | [string];
    entries: Array<_TimesheetEntry>;
    employeeId: string;
    managerComment: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_TimesheetStatus_n79(_uploadFile, _downloadFile, value.status),
        employeeUsername: value.employeeUsername,
        weekStartDate: value.weekStartDate,
        totalHours: value.totalHours,
        submittedAt: value.submittedAt,
        hrComment: value.hrComment ? candid_some(value.hrComment) : candid_none(),
        entries: value.entries,
        employeeId: value.employeeId,
        managerComment: value.managerComment ? candid_some(value.managerComment) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    status: ShiftStatus;
    endTime: bigint;
    date: bigint;
    employeeId: string;
    department: string;
}): {
    id: string;
    startTime: bigint;
    status: _ShiftStatus;
    endTime: bigint;
    date: bigint;
    employeeId: string;
    department: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: to_candid_ShiftStatus_n9(_uploadFile, _downloadFile, value.status),
        endTime: value.endTime,
        date: value.date,
        employeeId: value.employeeId,
        department: value.department
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShiftStatus): {
    published: null;
} | {
    draft: null;
} {
    return value == ShiftStatus.published ? {
        published: null
    } : value == ShiftStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    supervisor: null;
} | {
    manager: null;
} | {
    hrAdmin: null;
} | {
    employee: null;
} {
    return value == Role.supervisor ? {
        supervisor: null
    } : value == Role.manager ? {
        manager: null
    } : value == Role.hrAdmin ? {
        hrAdmin: null
    } : value == Role.employee ? {
        employee: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmployeeStatus): {
    active: null;
} | {
    terminated: null;
} | {
    inactive: null;
} {
    return value == EmployeeStatus.active ? {
        active: null
    } : value == EmployeeStatus.terminated ? {
        terminated: null
    } : value == EmployeeStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobPostingStatus): {
    closed: null;
} | {
    open: null;
} | {
    draft: null;
} {
    return value == JobPostingStatus.closed ? {
        closed: null
    } : value == JobPostingStatus.open ? {
        open: null
    } : value == JobPostingStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplicantStage): {
    hired: null;
} | {
    offer: null;
} | {
    screening: null;
} | {
    interview: null;
} | {
    applied: null;
} | {
    rejected: null;
} {
    return value == ApplicantStage.hired ? {
        hired: null
    } : value == ApplicantStage.offer ? {
        offer: null
    } : value == ApplicantStage.screening ? {
        screening: null
    } : value == ApplicantStage.interview ? {
        interview: null
    } : value == ApplicantStage.applied ? {
        applied: null
    } : value == ApplicantStage.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimeOffStatus): {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
} {
    return value == TimeOffStatus.pending ? {
        pending: null
    } : value == TimeOffStatus.denied ? {
        denied: null
    } : value == TimeOffStatus.approved ? {
        approved: null
    } : value;
}
function to_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimesheetStatus): {
    managerApproved: null;
} | {
    submitted: null;
} | {
    hrDenied: null;
} | {
    managerDenied: null;
} | {
    hrApproved: null;
} {
    return value == TimesheetStatus.managerApproved ? {
        managerApproved: null
    } : value == TimesheetStatus.submitted ? {
        submitted: null
    } : value == TimesheetStatus.hrDenied ? {
        hrDenied: null
    } : value == TimesheetStatus.managerDenied ? {
        managerDenied: null
    } : value == TimesheetStatus.hrApproved ? {
        hrApproved: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
