/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicantStage = IDL.Variant({
  'hired' : IDL.Null,
  'offer' : IDL.Null,
  'screening' : IDL.Null,
  'interview' : IDL.Null,
  'applied' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Applicant = IDL.Record({
  'id' : IDL.Text,
  'contact' : IDL.Text,
  'jobPostingId' : IDL.Text,
  'name' : IDL.Text,
  'resumeNotes' : IDL.Text,
  'stage' : ApplicantStage,
  'appliedDate' : IDL.Int,
});
export const PTOBalance = IDL.Record({
  'balance' : IDL.Float64,
  'employeeId' : IDL.Text,
  'policyId' : IDL.Text,
});
export const PTOPolicy = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'accrualRate' : IDL.Float64,
  'eligibleLeaveTypes' : IDL.Vec(IDL.Text),
  'maxCarryOver' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShiftStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Shift = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'status' : ShiftStatus,
  'endTime' : IDL.Int,
  'date' : IDL.Int,
  'employeeId' : IDL.Text,
  'department' : IDL.Text,
});
export const Role = IDL.Variant({
  'supervisor' : IDL.Null,
  'manager' : IDL.Null,
  'hrAdmin' : IDL.Null,
  'employee' : IDL.Null,
});
export const EmployeeStatus = IDL.Variant({
  'active' : IDL.Null,
  'terminated' : IDL.Null,
  'inactive' : IDL.Null,
});
export const Employee = IDL.Record({
  'id' : IDL.Text,
  'status' : EmployeeStatus,
  'role' : Role,
  'directManagerId' : IDL.Opt(IDL.Text),
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'jobTitle' : IDL.Text,
  'badgeId' : IDL.Text,
  'phone' : IDL.Text,
  'department' : IDL.Text,
  'startDate' : IDL.Int,
});
export const CreateEmployeeWithAccountInput = IDL.Record({
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'directManagerId' : IDL.Opt(IDL.Text),
  'passwordHash' : IDL.Text,
  'profile' : Employee,
});
export const JobPostingStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'draft' : IDL.Null,
});
export const JobPosting = IDL.Record({
  'id' : IDL.Text,
  'status' : JobPostingStatus,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'department' : IDL.Text,
});
export const ServiceResult_4 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Text,
});
export const TimeOffStatus = IDL.Variant({
  'pending' : IDL.Null,
  'denied' : IDL.Null,
  'approved' : IDL.Null,
});
export const TimeOffRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : TimeOffStatus,
  'endDate' : IDL.Int,
  'approverComments' : IDL.Opt(IDL.Text),
  'timeOffType' : IDL.Text,
  'employeeId' : IDL.Text,
  'requestDate' : IDL.Int,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'role' : Role,
  'employeeId' : IDL.Opt(IDL.Text),
});
export const ServiceResult_3 = IDL.Variant({
  'ok' : Employee,
  'err' : IDL.Text,
});
export const TimesheetStatus = IDL.Variant({
  'managerApproved' : IDL.Null,
  'submitted' : IDL.Null,
  'hrDenied' : IDL.Null,
  'managerDenied' : IDL.Null,
  'hrApproved' : IDL.Null,
});
export const TimesheetEntry = IDL.Record({
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
  'date' : IDL.Text,
  'hoursWorked' : IDL.Float64,
});
export const Timesheet = IDL.Record({
  'id' : IDL.Text,
  'status' : TimesheetStatus,
  'employeeUsername' : IDL.Text,
  'weekStartDate' : IDL.Text,
  'totalHours' : IDL.Float64,
  'submittedAt' : IDL.Int,
  'hrComment' : IDL.Opt(IDL.Text),
  'entries' : IDL.Vec(TimesheetEntry),
  'employeeId' : IDL.Text,
  'managerComment' : IDL.Opt(IDL.Text),
});
export const ServiceResult_1 = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const ServiceResult_2 = IDL.Variant({
  'ok' : UserProfile,
  'err' : IDL.Text,
});
export const ServiceResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApplicant' : IDL.Func([Applicant], [], []),
  'addPTOBalance' : IDL.Func([PTOBalance], [], []),
  'addPTOPolicy' : IDL.Func([PTOPolicy], [], []),
  'approveTimeOffRequest' : IDL.Func([IDL.Text], [], []),
  'approveTimeOffRequestWithComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignShift' : IDL.Func([Shift], [], []),
  'createAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
  'createEmployee' : IDL.Func([Employee], [], []),
  'createEmployeeWithAccount' : IDL.Func(
      [CreateEmployeeWithAccountInput],
      [],
      [],
    ),
  'createJobPosting' : IDL.Func([JobPosting], [], []),
  'deactivateEmployee' : IDL.Func([IDL.Text], [], []),
  'deleteEmployee' : IDL.Func([IDL.Text], [ServiceResult_4], []),
  'deleteShift' : IDL.Func([IDL.Text], [], []),
  'denyTimeOffRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllApplicants' : IDL.Func([], [IDL.Vec(Applicant)], ['query']),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllPTOPolicies' : IDL.Func([], [IDL.Vec(PTOPolicy)], ['query']),
  'getAllShiftsForDepartment' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Shift)],
      ['query'],
    ),
  'getAllShiftsForEmployee' : IDL.Func([IDL.Text], [IDL.Vec(Shift)], ['query']),
  'getAllTimeOffRequests' : IDL.Func([], [IDL.Vec(TimeOffRequest)], ['query']),
  'getAllTimeOffRequestsForEmployee' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimeOffRequest)],
      ['query'],
    ),
  'getApplicant' : IDL.Func([IDL.Text], [Applicant], ['query']),
  'getApplicantsForPosting' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Applicant)],
      ['query'],
    ),
  'getAvailableShifts' : IDL.Func([IDL.Text], [IDL.Vec(Shift)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
  'getEmployeeByBadgeId' : IDL.Func([IDL.Text], [ServiceResult_3], ['query']),
  'getEmployeesByRole' : IDL.Func([Role], [IDL.Vec(Employee)], ['query']),
  'getJobPosting' : IDL.Func([IDL.Text], [JobPosting], ['query']),
  'getPTOBalance' : IDL.Func([IDL.Text], [PTOBalance], ['query']),
  'getPTOPolicy' : IDL.Func([IDL.Text], [PTOPolicy], ['query']),
  'getTimesheets' : IDL.Func([], [IDL.Vec(Timesheet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasConflictingShift' : IDL.Func([Shift], [IDL.Bool], ['query']),
  'hrReviewTimesheet' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [ServiceResult_1],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
  'loginWithBadgeId' : IDL.Func([IDL.Text], [ServiceResult_2], []),
  'managerReviewTimesheet' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text],
      [ServiceResult_1],
      [],
    ),
  'publishSchedule' : IDL.Func([IDL.Text, IDL.Int], [ServiceResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRole' : IDL.Func([IDL.Text, Role], [], []),
  'submitTimeOffRequest' : IDL.Func([TimeOffRequest], [], []),
  'submitTimesheet' : IDL.Func([Timesheet], [ServiceResult_1], []),
  'unpublishSchedule' : IDL.Func([IDL.Text, IDL.Int], [ServiceResult], []),
  'updateApplicantStage' : IDL.Func([IDL.Text, ApplicantStage], [], []),
  'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
  'updateJobPosting' : IDL.Func([IDL.Text, JobPosting], [], []),
  'updatePTOBalance' : IDL.Func([PTOBalance], [], []),
  'updatePTOPolicy' : IDL.Func([PTOPolicy], [], []),
  'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicantStage = IDL.Variant({
    'hired' : IDL.Null,
    'offer' : IDL.Null,
    'screening' : IDL.Null,
    'interview' : IDL.Null,
    'applied' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Applicant = IDL.Record({
    'id' : IDL.Text,
    'contact' : IDL.Text,
    'jobPostingId' : IDL.Text,
    'name' : IDL.Text,
    'resumeNotes' : IDL.Text,
    'stage' : ApplicantStage,
    'appliedDate' : IDL.Int,
  });
  const PTOBalance = IDL.Record({
    'balance' : IDL.Float64,
    'employeeId' : IDL.Text,
    'policyId' : IDL.Text,
  });
  const PTOPolicy = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'accrualRate' : IDL.Float64,
    'eligibleLeaveTypes' : IDL.Vec(IDL.Text),
    'maxCarryOver' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShiftStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Shift = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'status' : ShiftStatus,
    'endTime' : IDL.Int,
    'date' : IDL.Int,
    'employeeId' : IDL.Text,
    'department' : IDL.Text,
  });
  const Role = IDL.Variant({
    'supervisor' : IDL.Null,
    'manager' : IDL.Null,
    'hrAdmin' : IDL.Null,
    'employee' : IDL.Null,
  });
  const EmployeeStatus = IDL.Variant({
    'active' : IDL.Null,
    'terminated' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const Employee = IDL.Record({
    'id' : IDL.Text,
    'status' : EmployeeStatus,
    'role' : Role,
    'directManagerId' : IDL.Opt(IDL.Text),
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'jobTitle' : IDL.Text,
    'badgeId' : IDL.Text,
    'phone' : IDL.Text,
    'department' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const CreateEmployeeWithAccountInput = IDL.Record({
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'directManagerId' : IDL.Opt(IDL.Text),
    'passwordHash' : IDL.Text,
    'profile' : Employee,
  });
  const JobPostingStatus = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'draft' : IDL.Null,
  });
  const JobPosting = IDL.Record({
    'id' : IDL.Text,
    'status' : JobPostingStatus,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'department' : IDL.Text,
  });
  const ServiceResult_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const TimeOffStatus = IDL.Variant({
    'pending' : IDL.Null,
    'denied' : IDL.Null,
    'approved' : IDL.Null,
  });
  const TimeOffRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : TimeOffStatus,
    'endDate' : IDL.Int,
    'approverComments' : IDL.Opt(IDL.Text),
    'timeOffType' : IDL.Text,
    'employeeId' : IDL.Text,
    'requestDate' : IDL.Int,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'role' : Role,
    'employeeId' : IDL.Opt(IDL.Text),
  });
  const ServiceResult_3 = IDL.Variant({ 'ok' : Employee, 'err' : IDL.Text });
  const TimesheetStatus = IDL.Variant({
    'managerApproved' : IDL.Null,
    'submitted' : IDL.Null,
    'hrDenied' : IDL.Null,
    'managerDenied' : IDL.Null,
    'hrApproved' : IDL.Null,
  });
  const TimesheetEntry = IDL.Record({
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
    'date' : IDL.Text,
    'hoursWorked' : IDL.Float64,
  });
  const Timesheet = IDL.Record({
    'id' : IDL.Text,
    'status' : TimesheetStatus,
    'employeeUsername' : IDL.Text,
    'weekStartDate' : IDL.Text,
    'totalHours' : IDL.Float64,
    'submittedAt' : IDL.Int,
    'hrComment' : IDL.Opt(IDL.Text),
    'entries' : IDL.Vec(TimesheetEntry),
    'employeeId' : IDL.Text,
    'managerComment' : IDL.Opt(IDL.Text),
  });
  const ServiceResult_1 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const ServiceResult_2 = IDL.Variant({ 'ok' : UserProfile, 'err' : IDL.Text });
  const ServiceResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApplicant' : IDL.Func([Applicant], [], []),
    'addPTOBalance' : IDL.Func([PTOBalance], [], []),
    'addPTOPolicy' : IDL.Func([PTOPolicy], [], []),
    'approveTimeOffRequest' : IDL.Func([IDL.Text], [], []),
    'approveTimeOffRequestWithComment' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignShift' : IDL.Func([Shift], [], []),
    'createAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Role], [], []),
    'createEmployee' : IDL.Func([Employee], [], []),
    'createEmployeeWithAccount' : IDL.Func(
        [CreateEmployeeWithAccountInput],
        [],
        [],
      ),
    'createJobPosting' : IDL.Func([JobPosting], [], []),
    'deactivateEmployee' : IDL.Func([IDL.Text], [], []),
    'deleteEmployee' : IDL.Func([IDL.Text], [ServiceResult_4], []),
    'deleteShift' : IDL.Func([IDL.Text], [], []),
    'denyTimeOffRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllApplicants' : IDL.Func([], [IDL.Vec(Applicant)], ['query']),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllPTOPolicies' : IDL.Func([], [IDL.Vec(PTOPolicy)], ['query']),
    'getAllShiftsForDepartment' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Shift)],
        ['query'],
      ),
    'getAllShiftsForEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Shift)],
        ['query'],
      ),
    'getAllTimeOffRequests' : IDL.Func(
        [],
        [IDL.Vec(TimeOffRequest)],
        ['query'],
      ),
    'getAllTimeOffRequestsForEmployee' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimeOffRequest)],
        ['query'],
      ),
    'getApplicant' : IDL.Func([IDL.Text], [Applicant], ['query']),
    'getApplicantsForPosting' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Applicant)],
        ['query'],
      ),
    'getAvailableShifts' : IDL.Func([IDL.Text], [IDL.Vec(Shift)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEmployee' : IDL.Func([IDL.Text], [Employee], ['query']),
    'getEmployeeByBadgeId' : IDL.Func([IDL.Text], [ServiceResult_3], ['query']),
    'getEmployeesByRole' : IDL.Func([Role], [IDL.Vec(Employee)], ['query']),
    'getJobPosting' : IDL.Func([IDL.Text], [JobPosting], ['query']),
    'getPTOBalance' : IDL.Func([IDL.Text], [PTOBalance], ['query']),
    'getPTOPolicy' : IDL.Func([IDL.Text], [PTOPolicy], ['query']),
    'getTimesheets' : IDL.Func([], [IDL.Vec(Timesheet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasConflictingShift' : IDL.Func([Shift], [IDL.Bool], ['query']),
    'hrReviewTimesheet' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [ServiceResult_1],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(UserProfile)], []),
    'loginWithBadgeId' : IDL.Func([IDL.Text], [ServiceResult_2], []),
    'managerReviewTimesheet' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text],
        [ServiceResult_1],
        [],
      ),
    'publishSchedule' : IDL.Func([IDL.Text, IDL.Int], [ServiceResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRole' : IDL.Func([IDL.Text, Role], [], []),
    'submitTimeOffRequest' : IDL.Func([TimeOffRequest], [], []),
    'submitTimesheet' : IDL.Func([Timesheet], [ServiceResult_1], []),
    'unpublishSchedule' : IDL.Func([IDL.Text, IDL.Int], [ServiceResult], []),
    'updateApplicantStage' : IDL.Func([IDL.Text, ApplicantStage], [], []),
    'updateEmployee' : IDL.Func([IDL.Text, Employee], [], []),
    'updateJobPosting' : IDL.Func([IDL.Text, JobPosting], [], []),
    'updatePTOBalance' : IDL.Func([PTOBalance], [], []),
    'updatePTOPolicy' : IDL.Func([PTOPolicy], [], []),
    'validateSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };